- name: 'Create some aws ec2 instances with docker'
  hosts: local
  connection: local
  gather_facts: False
  tags: provisioning

  tasks:

    - name: 'Create EC2 cluster emqx instances'
      include_role:
        name: ec2-instance
      vars:
        instance_name: Docker-EC2
        region: eu-central-1
        key_name: id_rsa
        instance_type: t2.micro
        instances_count: 3
        security_groups: [test]
        subnets:
          - subnet-8bdf3af1


    - name: "Add mqqt cluster hosts to install"
      add_host:
        name: "{{item.instances[0].public_ip}}"
        ansible_host: "{{item.instances[0].public_ip}}"
        group: new-ec2-instances
      with_items: "{{ec2.results}}"



- hosts: new-ec2-instances
  gather_facts: False
  roles:
    - docker
    - serverApp
  become: true
  tasks:

    - name: 'Wait for app server port will be avaliable'
      wait_for:
        host: localhost
        port: 5050
        state: started

    - name: 'Wait'
      pause:
        seconds: 10

    - name: 'Check server'
      uri:
        url: http://localhost:5050
      register: curl_out


    - name: 'Show debug info from curl'
      debug: var=curl_out
